### ISSUE TITLE
conflict in declaration of :root

### ISSUE THREAD

**Issue by theCrab** [jamonholmgren/promotion-motion-kit#2]
@jamonholmgren How comes you are setting the root context in `on_load` and in the `layout`? Am I missing something?

I keep getting the error
```sh
tree_layout.rb:112:in `root:': Already created the root view (MotionKit::ContextConflictError)
```
Here is my [sample app](/thecrab/padrikit) 

**Intent**
I would like to make the views appear on top of the mapview and still retain touch access on the map. At the moment whenever I succeed to show the views the map is not accessible. Seams like another view is sitting on top of the map.

Any tips?

**Comment by theCrab** [comment]
Also, what is the best way to show and hide those views dynamically using buttons? cc/ @colinta

**Comment by jamonholmgren** [comment]
@theCrab Hey, sorry, just saw this!

I unfortunately am not using MotionKit anymore (or RubyMotion, for that matter). I don't remember why I set the root context there.

If you want to file an issue on https://github.com/motion-kit/motion-kit I think Colin might be able to help you out.

Sorry about that!
